filter:
    excluded_paths:
        - 'bin/*'
        - 'build/*'
        - 'debian/*'
        - 'dev/*'
        - 'dist/*'
        - 'doc/*'
        - 'etc/*'
        - 'fifo/*'
        - 'lib/exabgp/vendoring/*'
        - 'logo/*'
        - 'qa/*'
        - 'redhat/*'
        - 'run/*'
        - 'sbin/*'
        - 'service/*'
    paths: {  }
tools:
    python_analyzer:
        enabled: true
        config:
            metrics: true
            duplication_detector:
                enabled: true
                min_mass: 25
        file_extensions:
            - .py
        filter:
            excluded_paths:
                - 'bin/*'
                - 'build/*'
                - 'debian/*'
                - 'dev/*'
                - 'dist/*'
                - 'doc/*'
                - 'etc/*'
                - 'fifo/*'
                - 'lib/exabgp/vendoring/*'
                - 'logo/*'
                - 'qa/*'
                - 'redhat/*'
                - 'run/*'
                - 'sbin/*'
                - 'service/*'
            paths: {  }
    pylint:
        enabled: true
        python_version: '3'
        plugins: {  }
        config_file: '.pylintrc'
        filter:
            excluded_paths:
                - 'bin/*'
                - 'build/*'
                - 'debian/*'
                - 'dev/*'
                - 'dist/*'
                - 'doc/*'
                - 'etc/*'
                - 'fifo/*'
                - 'lib/exabgp/vendoring/*'
                - 'logo/*'
                - 'qa/*'
                - 'redhat/*'
                - 'run/*'
                - 'sbin/*'
                - 'service/*'
            paths: {  }
    external_code_coverage:
        timeout: 600
