.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EXABGP 1 "April 21, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
exabgp \- BGP route injector
.SH SYNOPSIS
.B exabgp
.RI <configfile>
.SH DESCRIPTION
This manual page documents briefly the
.B exabgp
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBexabgp\fP is a BGP route injector.
 The route injector can connect using either IPv4 or IPv6 and announce both IPv4 and IPv6 routes.
 Potential use are :
 - Injection of service IPs like AS112 announcement
 - Temporary route redirection: more specific routes with different next-hop
 - Injection of flow routes to handle DDOS
.SH AUTHOR
exabgp was written by Thomas Mangin <thomas.mangin@exa-networks.co.uk>.
.PP
This manual page was written by Henry-Nicolas Tourneur <henry.nicolas@tourneur.be>,
for the Debian project (and may be used by others).
