process announce-routes {
	run ./run/api-disable.run;
	encoder json;
	respawn false;
}

neighbor 127.0.0.1 {
	router-id 1.2.3.4;
	local-address 127.0.0.1;
	local-as 1;
	peer-as 1;
	group-updates false;
	# issue #1013: no session until the API process has loaded its routes
	shutdown true;
	capability {
		graceful-restart disable;
	}

	family {
		ipv4 unicast;
	}
	api {
		processes [ announce-routes ];
		neighbor-changes;
		send {
			parsed;
			update;
		}
	}
}
