neighbor 127.0.0.1 {
	router-id 10.0.0.2;
	local-address 127.0.0.1;
	local-as 65533;
	peer-as 65533;
	hold-time 180;

	capability {
		add-path send/receive;
	}

	family {
		ipv4 unicast;
		ipv6 unicast;
	}

	add-path {
		ipv4 unicast limit 10;
		ipv6 unicast;
	}
}
