neighbor 127.0.0.1 {
	router-id 10.0.0.2;
	local-address 127.0.0.1;
	local-as 65001;
	peer-as 64999;
	hold-time 180;

	confederation {
		identifier 65000;
		members [ 65002 65003 ];
	}

	family {
		ipv4 unicast;
	}

	static {
		route 10.0.0.0/24 next-hop 10.0.1.254;
		route 10.0.1.0/24 next-hop 10.0.1.254 as-path confed-sequence [ 65001 ] [ 65000 100 ];
	}
}
