#!/bin/sh

path="$(readlink -f "$(dirname "$0")"/..)"

export PYTHONPATH=$path/lib:/usr/share/exabgp/lib/3.4.4

for INTERPRETER in "$INTERPRETER" pypy python2.7 python2.6 python2 python; do
	INTERPRETER="$(command -v "$INTERPRETER")" && break
done

APPLICATION="$("$INTERPRETER" -c "
import sys
import os

print [os.path.join(_, 'exabgp', 'application', 'bmp.py')
       for _ in sys.path
       if os.path.isfile('/'.join((_, 'exabgp', 'application', 'bmp.py')))][0]
")"

echo exec "$INTERPRETER" "$APPLICATION" "$@"
