#!/bin/sh

set -e

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
    for f in processes/dynamic-1.sh processes/watchdog-1.sh; do
        if ! egrep -q "$f" /etc/exabgp/exabgp.conf 2> /dev/null ; then
            dpkg-maintscript-helper rm_conffile "$f" -- "$@" ; fi
    done
    dpkg-maintscript-helper rm_conffile /etc/default/exabgp -- "$@"
    dpkg-maintscript-helper rm_conffile /etc/exabgp/exabgp.conf -- "$@"
fi

#DEBHELPER#

exit 0
