#!/bin/sh

set -e

CONFIGFILE="/etc/exabgp/exabgp.env"
TMPCONF="/etc/exabgp/exabgp.env.dpkg-tmp"

gen_env_config() {
    echo "Generating /etc/exabgp/exabgp.env."
    trap 'rm -f $TMPCONF' TERM INT EXIT QUIT
    exabgp --fi >> "$TMPCONF" 2>/dev/null
    sed -i "s#nobody#exabgp#" "$TMPCONF"
    ucf $TMPCONF $CONFIGFILE
    rm -f $TMPCONF
}

case "$1" in
configure)
    adduser --quiet --system --group --disabled-login --home /run/exabgp exabgp
    gen_env_config
    ;;
esac

#DEBHELPER#

exit 0
