#!/bin/sh

ip=`ifconfig | grep -A5 en0 | grep "inet " | awk '{ print $2; }'`
cat second.template | sed -e "s/IP/$ip/" > second.conf

env exabgp.tcp.bind="$ip" exabgp.tcp.port=1790 ../../../sbin/exabgp second.conf -d
