#!/usr/bin/env python

import sys
import time

messages = [
'announce route 1.0.0.0/21 next-hop 101.1.101.1 med 200 community [2:1] split /24',
'announce route 1.1.0.0/16 next-hop 101.1.101.1',
'announce route 1.2.0.0/22 next-hop 101.1.101.1 split /24',
'announce route 1.3.0.0/16 next-hop 101.1.101.1 split /24',
'announce route 1.4.0.0/16 next-hop 101.1.101.1 med 200',
'announce route 1.5.0.0/16 next-hop 101.1.101.1 community [2:1]',
'announce route 1.6.0.0/21 next-hop 101.1.101.1 med 200 community [2:1]',
]

while messages:
	message = messages.pop(0)
	sys.stdout.write( message + '\n')
	sys.stdout.flush()
	time.sleep(0.1)

while True:
	time.sleep(1)

