#!/usr/bin/env python

import sys
import pstats

prg = sys.argv[0]

try:
	name = sys.argv[1]
except IndexError:
	print "%s <filename> [<number> [<field>]] " % prg
	print "%s   -^" % (' '*len(prg))
	sys.exit(1)

try:
	number = int(sys.argv[2])
except ValueError:
	print "%s <filename> [<number> [<field>]] " % prg
	print "%s              -^" % (' '*len(prg))
	sys.exit(1)
except IndexError:
	number = 0

try:
	field = sys.argv[3]
except IndexError:
	field = 'time'

options = ['time','calls']

if field not in options:
	print 'invalid sorting field, valid enties %s' % ', '.join(options)
	sys.exit(1)

try:
	stats = pstats.Stats(name)
except IOError:
	print "can not open the file %s" % name
	sys.exit(1)

if number:
	print stats.strip_dirs().sort_stats(field).print_stats(number)
else:
	print stats.print_stats()
