when:
  - event: push
    branch: [main, 5.0, 4.2, 3.4]
  - event: pull_request
    branch: main

steps:
  - name: lint
    image: python:3.12-bookworm
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - uv sync --frozen
      - python --version
      - uv run ruff --version
      - uv run ruff check src qa tests --output-format=full --statistics
