when:
  - event: push
    branch: [main, 5.0, 4.2, 3.4]
  - event: pull_request
    branch: main

matrix:
  PYTHON_VERSION:
    - "3.12"
    - "3.13"
    - "3.14"

steps:
  - name: pytest
    image: python:${PYTHON_VERSION}-bookworm
    commands:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - uv sync --frozen
      - python --version
      - env PYTHONPATH=src exabgp_log_enable=false uv run pytest --cov --cov-reset ./tests/unit/test_*.py ./tests/fuzz/test_*.py
