"""The syntax block of exabgp.conf(5) is what the grammar reads, not what someone remembered.

It was written by hand and drifted: `rate-limit <enable | disable>` where a number is read,
`encoding <text | json>` for a statement called `encoder`.  The block between the markers is
now printed from the grammar (`qa/bin/update_man_syntax`), and this test fails the day the
grammar and the page disagree.
"""

from __future__ import annotations

import os

from exabgp.configuration.grammar.describe import manual, syntax
from exabgp.configuration.grammar.tree.root import ROOT

PAGE = os.path.join(os.path.dirname(__file__), '..', '..', 'doc', 'man', 'exabgp.conf.5')
START = '.\\" syntax: generated by qa/bin/update_man_syntax, do not edit'
END = '.\\" syntax: end'
WIDTH = 78  # what a terminal shows without wrapping a literal line


def block() -> list[str]:
    with open(PAGE, encoding='utf-8') as page:
        lines = page.read().splitlines()
    assert START in lines and END in lines, 'the markers around the generated block are gone'
    return lines[lines.index(START) + 1 : lines.index(END)]


def test_the_page_shows_what_the_grammar_reads() -> None:
    expected = manual(syntax(ROOT), WIDTH)
    assert block() == expected, 'run qa/bin/update_man_syntax'


def test_no_line_of_the_block_is_wider_than_a_terminal() -> None:
    assert [line for line in manual(syntax(ROOT), WIDTH) if len(line) > WIDTH] == []


def test_a_request_is_never_read_from_the_block() -> None:
    """mdoc takes a line starting with a dot or a quote as a request, and eats it."""
    for line in manual(syntax(ROOT), WIDTH):
        assert not line.startswith(('.', "'")), line
        assert '\\' not in line, line


def test_the_old_mistakes_are_gone() -> None:
    text = '\n'.join(block())
    assert 'rate-limit <number>|disable;' in text
    assert 'rate-limit <enable' not in text
    assert 'encoder text|json;' in text


def test_a_wide_statement_without_a_note_is_carried_on() -> None:
    statement = 'bgp-prefix-sid [ <label-index> ] | [ <label-index>, [ ( <base>,<range> ) ... ] ];'
    lines = manual(['\t\t\t' + statement], WIDTH)
    assert len(lines) > 1
    assert all(len(line) <= WIDTH for line in lines)
