#!/usr/bin/env python

import sys
import time
import json

time.sleep(3)

while True:
	line = sys.stdin.readline()
	time.sleep(1)
	if line:
		break

try:
	print >> sys.stderr, 'json received:', line.rstrip()
	print >> sys.stderr, 'json decoded :', json.loads(line)

	time.sleep(1)

	sys.stdout.write('announce route 1.1.1.1/32 next-hop 101.1.101.1 med 200\n')
	sys.stdout.flush()
except:
	print >> sys.stderr, 'failure, json can not be decoded'

while True:
	sys.stdin.readline()
