#!/usr/bin/env python

import sys
import time

messages = [
	'neighbor 127.0.0.1 announce vpls endpoint 5 base 10702 offset 1 size 8 next-hop 192.168.201.1 origin igp as-path [ 30740 30740 30740 30740 30740 30740 30740 ] local-preference 100 med 2000 rd 192.168.201.1:123 community [ 54591:123] extended-community [ target:54591:6 l2info:19:0:1500:111] originator-id 192.168.22.1 cluster-list [ 3.3.3.3 192.168.201.1 ]',
	'neighbor 127.0.0.1 withdraw vpls endpoint 5 base 10702 offset 1 size 8 next-hop 192.168.201.1 origin igp as-path [ 30740 30740 30740 30740 30740 30740 30740 ] local-preference 100 med 2000 rd 192.168.201.1:123 community [ 54591:123] extended-community [ target:54591:6 l2info:19:0:1500:111] originator-id 192.168.22.1 cluster-list [ 3.3.3.3 192.168.201.1 ]',
]

while messages:
	time.sleep(2)
	message = messages.pop(0)
	sys.stdout.write(message + '\n')
	sys.stdout.flush()

counter = 0
while True:
	try:
		while True:
			line = sys.stdin.readline().strip()
			if line:
				break
			counter += 1
			if counter > 100:
				sys.exit(1)
		counter = 0
		time.sleep(0.5)
	except KeyboardInterrupt:
		pass
	except IOError:
		# most likely a signal during readline
		pass
