#!/usr/bin/env python

import sys

# When the parent dies we are seeing continual newlines, so we only access so many before stopping
counter = 0

while True:
	try:
		line = sys.stdin.readline().strip()

		if not 'shutdown' in line:
			print >> sys.stderr, 'failure, we received data on this worker: ', line
			sys.stderr.flush()

			print "announce route 6.6.6.6/6 next-hop 9.9.9.9"
			sys.stdout.flush()

		if line == "":
			counter += 1
			if counter > 100:
				break
			continue

		counter = 0
	except KeyboardInterrupt:
		pass
	except IOError:
		# most likely a signal during readline
		pass
