#!/usr/bin/env python3

import time

from exabgp_api import send, wait_for_ack, wait_for_shutdown


def main() -> None:
    # neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 1 peer-as 1 router-id 1.2.3.4 family-allowed ipv4-unicast
    messages = [
        'announce                                                                              route 1.0.0.0/24 next-hop 101.1.101.1 med 200 community [2:1]',
        'neighbor 127.0.0.1 announce                                                           route 1.1.0.0/24 next-hop 101.1.101.1',
        'neighbor 127.0.0.1 local-as 1 family-allowed ipv4-unicast announce                    route 1.2.0.0/24 next-hop 101.1.101.1',
        'neighbor 127.0.0.1 local-as 1 family-allowed in-open announce                         route 9.9.9.9/24 next-hop 101.1.101.1',
        'neighbor 127.0.0.1 local-as 1 peer-as 1 local-ip 127.0.0.1 router-id 1.2.3.4 announce route 1.3.0.0/24 next-hop 101.1.101.1',
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_ack(expected_count=5)
    wait_for_shutdown()


if __name__ == '__main__':
    main()
