#!/usr/bin/env python3

import time

from exabgp_api import flush, wait_for_shutdown


def main() -> None:
    # we do not announce withdraw on the first run of the reactor

    messages1 = [
        'announce route 1.1.0.0/24 next-hop 101.1.101.1',
        'announce route 1.1.0.0/25 next-hop 101.1.101.1',
        'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
        'announce route 1.1.0.0/25 next-hop 101.1.101.1',
    ]

    messages2 = [
        'announce route 2.2.0.0/25 next-hop 101.1.101.1',
        'announce route 2.2.0.0/24 next-hop 101.1.101.1',
        'withdraw route 2.2.0.0/25 next-hop 101.1.101.1',
    ]

    messages3 = [
        'announce route 0.0.0.0/0  next-hop 1.101.1.101',
    ]

    time.sleep(0.2)

    flush('\n'.join(messages1) + '\n')
    time.sleep(0.2)

    flush('\n'.join(messages2) + '\n')
    time.sleep(0.2)

    for message in messages3:
        flush(message + '\n')

    wait_for_shutdown()


if __name__ == '__main__':
    main()
