#!/usr/bin/env python3

import time

from exabgp_api import send, wait_for_shutdown


def main() -> None:
    messages = [
        'neighbor 127.0.0.1 announce route 1.1.0.0/24 next-hop 101.1.101.1',
        'neighbor 127.0.0.1 router-id 1.2.3.4, neighbor 127.0.0.1 announce route 1.1.0.0/25 next-hop 101.1.101.1',
        'withdraw route 1.1.0.0/24 next-hop 101.1.101.1',
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_shutdown()


if __name__ == '__main__':
    main()
