#!/usr/bin/env python3

import time

from exabgp_api import send, wait_for_ack, wait_for_shutdown


def main() -> None:
    messages = [
        'announce route 3.0.0.0/24 next-hop 4.0.0.0',
    ]

    time.sleep(2)  # let some time for the config to be sent

    for message in messages:
        send(message)
        time.sleep(0.2)

    wait_for_ack(expected_count=1)
    wait_for_shutdown()


if __name__ == '__main__':
    main()
