#!/usr/bin/env python3

import time

from exabgp_api import send, wait_for_ack, wait_for_shutdown


def main() -> None:
    messages = [
        'neighbor 127.0.0.1 announce attributes path-information 1.2.3.4 next-hop 10.11.12.13 community [14:15] local-preference 16 nlri 16.17.18.19/32 20.21.22.23/32',
        'neighbor 127.0.0.1 announce attributes path-information 4.3.2.1 next-hop 10.11.12.13 community [14:15] local-preference 16 nlri 16.17.18.19/32 20.21.22.23/32',
    ]

    for message in messages:
        send(message)
        time.sleep(0.2)
        wait_for_ack(expected_count=1, timeout=0.3)

    wait_for_shutdown()


if __name__ == '__main__':
    main()
