#!/usr/bin/env python3

import time

from exabgp_api import send, wait_for_ack, wait_for_shutdown


def main() -> None:
    messages = [
        'announce route 1.0.0.0/21 next-hop 101.1.101.1 med 200 community [2:1] split /23',
        'neighbor 127.0.0.1 announce route 1.1.0.0/16 next-hop 101.1.101.1',
        'neighbor 127.0.0.1 local-as 1 announce route 1.2.0.0/22 next-hop 101.1.101.1 split /24',
        'neighbor 127.0.0.1 peer-as 1 announce route 1.3.0.0/24 next-hop 101.1.101.1 split /25',
        'neighbor 127.0.0.1 local-ip 127.0.0.1 announce route 1.4.0.0/16 next-hop 101.1.101.1 med 200',
        'neighbor 127.0.0.1 router-id 1.2.3.4 announce route 1.5.0.0/16 next-hop 101.1.101.1 community [2:1]',
        'neighbor absentone local-as 1 peer-as 1 local-ip 127.0.0.1 router-id 1.2.3.4 announce route 9.9.9.9/21 next-hop 101.1.101.1 med 200 community [2:1]',
        'neighbor 127.0.0.1 local-as 1 peer-as 1 local-ip 127.0.0.1 router-id 1.2.3.4 announce route 1.6.0.0/21 next-hop 101.1.101.1 med 200 community [2:1]',
        'neighbor 127.0.0.1 local-as 2 peer-as 3 local-ip 127.0.0.1 router-id 1.2.3.4 announce route 1.8.0.0/21 next-hop 101.1.101.1 med 200 large-community [2914:1:0]',
    ]

    time.sleep(0.2)

    for message in messages:
        send(message)
        time.sleep(0.1)

    wait_for_ack(expected_count=6)
    wait_for_shutdown()


if __name__ == '__main__':
    main()
